### ISSUE TITLE
Starting expressive from subdirectory does not work

### ISSUE THREAD

**Issue by gbonnema** [zendframework/zend-expressive-skeleton#107]
Immediatly after installing expressive I can successfully execute the site from "composer serve" i.e. "php -S 0.0.0.0:8080 -t public/". However, when I sftp this site to my test server, I see the header without the logo plus the footer, but I get 404 in the contents. 

The testserver is configured so that I have a local directory (/home/guus/www) as document root. I insert the project below /home/guus/www/zf-tutorial-expressive.  P.S. I have no say over the document root, so I wanted to use subdirectories.

When opening the page the zend system gets started (it aparantly loads index.html), but somewhere along the lines it gets confused because I use subdirectories. 

The page URL I use is something like : http:.//guus.example.nl/zf-tutorial-expressive/public/.

I would appreciate any pointers.

**Comment by mtymek** [comment]
By default it does not work - you need some code that handles subdirectory. Try my library: https://github.com/mtymek/blast-base-url - it was build to solve this problem. 

More on this subject: http://zendframework.github.io/zend-expressive/cookbook/using-a-base-path/

**Comment by gbonnema** [comment]
Thank you very much, Mateusz. Checking it out. Will let you know.
