### ISSUE TITLE
What shall we do with the .travis.yml?

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-expressive-skeleton#112]
While i really do like the idea of having a .travis.yml file ready to use after creating a fresh project, i do wonder if we're able to let the ExpressiveInstaller remove [this line](https://github.com/zendframework/zend-expressive-skeleton/blob/master/.travis.yml#L15) or if it's worth the work. After all Travis isn't automatically enabled when a user creates a repo so we could assume that users check their setup before they activate travis for their project.
I'd prefer to make it idiot proof though... ;)

**Comment by xtreamwayz** [comment]
Good catch. I just looked at the ZendSkeletonApplication and it doesn't have any tests and thus not this problem. There is already something in place to remove text form the composer lock file, so it can be added easily. Other option is to remove the file.

**Comment by Koopzington** [comment]
If you decide to remove the file, don't forget the .coveralls.yml, phpcs.xml and phpunit.xml.dist ;)

**Comment by xtreamwayz** [comment]
Actually you would still need the last two since phpunit and php_codesniffer are installed anyway.
