### ISSUE TITLE
Error by use Expressive 2.0.1 with Skeleton Application

### ISSUE THREAD

**Issue by mano87** [zendframework/zend-expressive-skeleton#140]
Hello,
directly after the installation of the Skeleton Expressive Application I get the following error:

> [10-Mar-2017 09:24:30 UTC] PHP Fatal error: Class Zend\Stdlib\PriorityList contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Countable::�) in D:\webworkspace\projects\zend-skeleton\vendor\zendframework\zend-stdlib\src\PriorityList.php on line 15

Why?

**Comment by xtreamwayz** [comment]
What options did you choose during installation?

**Comment by weierophinney** [comment]
I've looked at `Zend\Stdlib\PriorityList`. It:

- implements `Countable` from PHP's SPL
- implements a `count()` method.

This sounds like an error with your PHP installation, to be honest. What version of PHP are you using?

**Comment by weierophinney** [comment]
Closing due to lack of clarifications.
