### ISSUE TITLE
Suggestion about config and data folder

### ISSUE THREAD

**Issue by jkhaled** [zendframework/zend-expressive-skeleton#144]
Hi,

I have some minor suggestion about expressive structure 
* I think changing the ```data``` folder to ```var``` is more convenient, based on the main purpose of this folder =>  caching.
* and also a minor change in structure ```configuration``` to make it more clear;

src
├── App
│   ├── config
│   │   ├── config.global.php
│   │   ├── config.local.php
│   │   └── template.global.php
│   ├── src
│   │   ├── ConfigProvider.php
│   ├──templates

```php
#ConfigProvider.php

namespace App;
use Zend\Expressive\ConfigManager\PhpFileProvider;
class ConfigProvider
{
    public function __invoke()
    {
        return (new PhpFileProvider(__DIR__ . '/../config/{{,*.}global,{,*.}local}.php'))();
    }
}

```

**Comment by weierophinney** [comment]
Thank you for the suggestions. However, at this time, we do not plan to incorporate them.
