### ISSUE TITLE
Can someone explain this folder structure?

### ISSUE THREAD

**Issue by exts** [zendframework/zend-expressive-skeleton#148]
/src/App
    /src/App/src
    /src/App/templates

Is this meant to be similar to the symfony bundle structure? Just trying to wrap my head around the original goal for the default folder structure.

**Comment by xtreamwayz** [comment]
That is not the default. The default is the flat structure. What you showed would be the modulair structure, like the one from ZF modules.

**Comment by weierophinney** [comment]
@exts The default when you create a new application is the flat directory structure, which will look like:

```text
src/
|- App/
   |- Action/
      - HomePageAction.php
```

One choice when installing is the _modular_ directory structure, which is _recommended_, but not the default. That structure is as you detail above:

```text
src/
|- App/
   |- src/
      |- Action/
         - HomePageAction.php
   |- templates/
```

This is the _modular_ directory structure, and allows you to have assets (such as templates) related to a specific set of code co-located with the source code.

Unlike a zend-mvc application, we did not choose to name the top-level directory `module`. This was for several reasons:

- Not having it named `module` allows for easily mixing library code alongside modules without confusion. As an example, if you have code that is common across a number of modules, or a set of middleware that is for an API only and which has no templates or other assets, there's no reason to do a modular structure for that particular namespace.
- We wanted to ensure developers migrating from Expressive 1 to Expressive 2 would not need to change their existing directory structure should they want to start using modules. V1 used a `src/` tree.
- It's easier to support a single directory for all source code, whether it's library code or modules, for purposes of tooling (such as module creation, middleware creation, etc.).

> Any best practices with using the module system?

One! Keep all code related to the given module in that module. That means things like:

- Entities
- Collections
- Middleware
- Service factories
- Tests
- Configuration (via the `ConfigProvider`)
- Templates
- module-specific assets (fonts, CSS, JS, etc.)

The rationale is that if the module becomes big enough or if you decide you want to re-use it, you should be able to split it out into its own project easily (as a git submodule, or an independent composer package), without needing to change its directory structure, and without needing to pull in code scattered elsewhere across your application (unless those are dependencies!).

**Comment by exts** [comment]
Thanks for the huge response @weierophinney, really digging expressive now that I kind of have my head wrapped around it :)
