### ISSUE TITLE
Question regarding module setup 

### ISSUE THREAD

**Issue by exts** [zendframework/zend-expressive-skeleton#150]
Sorry if this isn't a great question, just going to preface with I've never dealt with a modular system like this before.

So right now I'm working on my first expressive application and I've decided to use the modular folder structure instead of the expressive 1 setup. I have a user module registered using the module script which contains my user entities/repository and what ever other code I may need for managing user data. That's fine and straight forward, but I have code that's essentially not going to be its own module, core application code used across multiple modules.

So I created a 'Core' module and I've integrated a common db interface for communicating with doctrine, I could have just explicitly used doctrine, but I'm not sure if I'll ever swap it out or not. My folder structure for this is as follows:

- /src/Core
- /src/Core/Database
- /src/Core/Database/ConnectionInterface.php
- /src/Core/Database/Doctrine/DoctrineConnection.php
- /src/Core/Database/Doctrine/DoctrineConnectionFactory.php (which uses expressive style factories for communicating w/ the container and returning a new instance)

Everything works well, I setup the `ConnectionInterface => DoctrineConnectionFactory` inside ConfigProvider, but I'm ultimately wondering if this is the right approach to setting this up? Would it be better to drop the core module and create a database Module w/ a similar idea. Or keep Core for things specifically tailored to this application AND create a database module w/ a similar idea which would probably allow me to reuse the doctrine stuff in other applications as well.

**Comment by jkhaled** [comment]
Hi, 
what's the point of doing  ```ConnectionInterface => DoctrineConnectionFactory```
if the factory returns an instance of EntityManager you have just to mention it  ```EntityManager=>DoctrineConnectionFactory``` its more clear, I wonder why adding an abstraction level 
if you decide to use doctrine in the application.

**Comment by exts** [comment]
@jkhaled 

> but I'm not sure if I'll ever swap it out or not.

**Comment by jkhaled** [comment]
@exts 
But doctrine's complexity does not share same functionality as other ORM or even DB adapter, 
so grouping them under same interface won't really help you for swapping,

**Comment by exts** [comment]
Yeah you're probably right, but I'm looking for a response to my other question.

**Comment by xtreamwayz** [comment]
I think you are building wrappers around the wrong parts. I would leave doctrine alone and use [DASPRiD/container-interop-doctrine](https://github.com/DASPRiD/container-interop-doctrine). 

And to swap to something else in the future, create custom repository interfaces:
```
interface UserRepositoryInterface
{
    public function insert(User $user);

    public function update(User $user);

    public function delete(User $user);

    public function find($id);

    public function findAll();

    public function findBy($criteria, array $orderBy = null, $limit = null, $offset = null);

    public function findOneBy($criteria);
}
```

Then create repositories in which you inject the database adapter / entity manager:
```
class ZendDbUserRepository implements UserRepository
{
    private $db;

    private $hydrator;

    public function __construct(Adapter $adapter, HydratorInterface $hydrator)
    {
        $this->db = new Sql($adapter);
        $this->hydrator = $hydrator;
    }
```

In the container you use the interface and use the repository factory:
```
return [
    'dependencies' => [
        'factories' => [
            \Zend\Db\Adapter\Adapter::class => \Zend\Db\Adapter\AdapterServiceFactory::class,
            \App\Domain\User\UserRepositoryInterface::class => \App\Factory\Infrastructure\User\ZendDbUserRepository::class,
        ],
    ],
];
```

So if I need to change in the future I can create a `DoctrineUserRepository` class and use that class in the container.

There are probably better ways to do this, but this worked for a recent project.

**Comment by exts** [comment]
@xtreamwayz I'm using the module structure, not the other one.

Thanks for your input on doctrine, but you guys still haven't really answered my initial question so I'm going to rewrite it where it isn't focused solely on doctrine and db abstraction:

I have a lot of core application code that isn't specified to a specific module which will be reused across multiple modules. Is it fine to throw all that inside its own 'Core' module or should I create a namespace specifically for that application code. Since the way the module structure is setup w/ composer makes it so each module has its own namespace eg.: `Module\Classname` etc... I ask because it seems weird having a single class component sit in its own namespace.

**Comment by exts** [comment]
Guess there's no wrong way, I'll refactor if it doesn't work out. I really do like the idea of how expressive looks though.

**Comment by xtreamwayz** [comment]
As you said yourself, there is no wrong. There is no "golden" structure for all applications. Just use whatever fits your project. For myself I throw most stuff in an "App" module. Once related code grows too large or I need to reuse the exact same code, I'll refactor it into its own module.

**Comment by exts** [comment]
Yeah :), thanks for the help @xtreamwayz
