### ISSUE TITLE
Question: development.config.php vs development.local.php.dist

### ISSUE THREAD

**Issue by belgattitude** [zendframework/zend-expressive-skeleton#156]
Currently to enable development and Whoops, the skeleton installer suggest using two files:

- `./config/development.config.php.dist` -> `./config/development.config.php`
- `./config/autoload/development.local.php.dist` -> `./config/autoload/development.local.php.dist`

Is there any reason to not use only one ? 

Could we merge both in `./config/development.config.php.dist` and remove the other ? For example:

```php
use Zend\ConfigAggregator\ConfigAggregator;
use Zend\Expressive\Container;
use Zend\Expressive\Middleware\ErrorResponseGenerator;

return [
    'debug' => true,
    ConfigAggregator::ENABLE_CACHE => false,
    'dependencies' => [
        'invokables' => [
        ],
        'factories'  => [
            ErrorResponseGenerator::class       => Container\WhoopsErrorResponseGeneratorFactory::class,
            'Zend\Expressive\Whoops'            => Container\WhoopsFactory::class,
            'Zend\Expressive\WhoopsPageHandler' => Container\WhoopsPageHandlerFactory::class,
        ],
    ],
    'whoops' => [
        'json_exceptions' => [
            'display'    => true,
            'show_trace' => true,
            'ajax_only'  => true,
        ],
    ],
];
```

**Comment by froschdesign** [comment]
@belgattitude 
> Is there any reason to not use only one ?

You will find the explanation in `./config/development.config.php.dist`:

```php
/**
 * For use with the zf-development-mode tool.
 *
 * Provide your own development-mode settings by editing the file
 * `config/autoload/development.local.php.dist`.
 *
 * Because this file is aggregated last, it simply ensures:
```

https://github.com/zendframework/zend-expressive-skeleton/blob/master/config/development.config.php.dist#L6

**Comment by belgattitude** [comment]
Thanks @froschdesign 

Make sense, I'll close it then.
