### ISSUE TITLE
HomePageFactory uses Interop ContainerInterface

### ISSUE THREAD

**Issue by shadowhand** [zendframework/zend-expressive-skeleton#159]
[This line](https://github.com/zendframework/zend-expressive-skeleton/blob/ecac3e40718dcc6b0478cc758022acd6ccb72da1/src/App/src/Action/HomePageFactory.php#L5) makes it impossible to use a container that implements `psr/container` but not `container-interop/container-interop`.

**Comment by xtreamwayz** [comment]
Fixed with #160 and merged into develop.
