### ISSUE TITLE
Cannot composer create project anymore

### ISSUE THREAD

**Issue by bartmcleod** [zendframework/zend-expressive-skeleton#162]
A few weeks ago I could `composer create project zendframework/zend-expressive-skeleton`, but now I get `Could not find package project with stability stable.`

Also, when specifying <project path> composer sees that as a version number.

**Comment by bartmcleod** [comment]
Ok, so I messed up the command, it should read `composer create-project` (with the dash -)

**Comment by Ocramius** [comment]
What is the resolution here?

**Comment by asgrim** [comment]
@Ocramius it's a non-issue; just typo in running the command.

**Comment by bartmcleod** [comment]
@Ocramius What @asgrim says.

**Comment by Ocramius** [comment]
Sorry, got the mails in a messed up order :-)
