### ISSUE TITLE
Add unit tests to enforce containers behave the same

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/zend-expressive-skeleton#167]
It seems that there might be inconsistency between containers. Specifically the open PR for auryn. It doesn't seem to share instances by default. I haven't tried it myself yet as the last time I tried it I couldn't get it working.

To enforce consistency between containers we could add a few unit tests to make sure all supported containers behave the same and support these configuration keys (if the container supports them):

- services
- factories
- invokables
- delegators
- aliases
- shared
- shared_by_default

**Comment by Ocramius** [comment]
Just cross-linking: https://discourse.zendframework.com/t/shared-instances-and-containerinterface/200/3
