### ISSUE TITLE
Should actions not implement Zend\Stratigility\MiddlewareInterface?

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive-skeleton#19]
I wonder, if it would make sense, if the `HomePageAction` and `PingAction` implement the `Zend\Stratigility\MiddlewareInterface`.

**Comment by weierophinney** [comment]
No. In fact, I was against adding that interface from the beginning, and only did it under pressure from a number of vocal contributors. Requiring usage of the interface makes it far more difficult to share middleware between different middleware runners, and it's why Stratigility itself does not *require* usage of the MiddlewareInterface, but instead looks only for a callable.

**Comment by RalfEggert** [comment]
Thanks for clarification. That makes sense! :-)
