### ISSUE TITLE
Uncaught Error: Call to undefined method Zend\ComponentInstaller\Injector\ConfigInjectorChain::getConfigFile() when require followed with unrequire component

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive-skeleton#198]
step to reproduce:

1. install zend-expressive 3

```
composer create-project "zendframework/zend-expressive-skeleton:3.0.x-dev" expressive-3.0-dev
```

2. require component 

```bash
composer require zendframework/zend-expressive-session:^1.0.0-dev
```

the component installed and updated to `config/config.php`. 

3. remove the component from composer.json and run : 

```bash
composer update 
```

got error : 

```bash
PHP Fatal error:  Uncaught Error: Call to undefined method Zend\ComponentInstaller\Injector\ConfigInjectorChain::getConfigFile() in /Users/samsonasik/www/expressive-3.0-dev/vendor/zendframework/zend-component-installer/src/ComponentInstaller.php:544
```

**Comment by xtreamwayz** [comment]
I can't reproduce this, but I know I had the same issue before 2 weeks ago. Also for me your require command didn't work. I had to do this: 

`composer require zendframework/zend-expressive-session:^1.0.x-dev`

When using that it did work as expected.

**Comment by samsonasik** [comment]
the issue happen when after component installed, then open composer.json -> remove component -> run composer update

**Comment by weierophinney** [comment]
@samsonasik That sounds like an issue with zend-component-installer, then. Can you open an issue there, please?

**Comment by samsonasik** [comment]
@weierophinney the issue seems already in zend-component-intaller repo https://github.com/zendframework/zend-component-installer/issues/39
