### ISSUE TITLE
v3 error: Error: Call to undefined method Zend\Expressive\Application::pipeRoutingMiddleware() line 41

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive-skeleton#210]
step to reproduce:

```
composer create-project      "zendframework/zend-expressive-skeleton:3.0.x-dev"      expressive-3.0-dev-1
```

after installed, and run `php -S localhost:8080 -t public/`, I got error: 

```
 Error: Call to undefined method Zend\Expressive\Application::pipeRoutingMiddleware() in /Users/samsonasik/www/expressive-3.0-dev-1/config/pipeline.php on line 41
```
It seems on installation process, the `config/pipeline.php` uses old `$app->pipeRoutingMiddleware()` in compare with latest `config/pipeline.php`: https://github.com/zendframework/zend-expressive-skeleton/blob/e3465a736dde215cf81c464d74532a761d3515bd/config/pipeline.php

**Comment by xtreamwayz** [comment]
I cannot reproduce this. Can you run `composer clearcache` once and create the project again?

I find this very strange as the pipeline is never been copied. It's always the same file.

**Comment by samsonasik** [comment]
Thank you, clear cache fix the error.
