### ISSUE TITLE
Incorrect Path

### ISSUE THREAD

**Issue by rettal** [zendframework/zend-expressive-skeleton#22]
Hi,

When you run app for first time after running commands from readme you get the following error:

Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Zend\Expressive\Application' in ....

I found that in Container.php the path is incorrect:

// Load configuration
$config = require 'config.php';

When it should be:

// Load configuration
$config = require 'config/config.php';

Because we chdir in index.php.

:)

**Comment by weierophinney** [comment]
This is only an issue in environments with non-standard `include_path` settings (typically, the current directory is checked, then the current working directory, and finally the include path). However, this has already been reported, and we have a patch in #21 that resolves the issue for such environments.

**Comment by rettal** [comment]
Ok Thanks.
