### ISSUE TITLE
PHP 7.2 - Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by brock0124** [zendframework/zend-expressive-skeleton#249]
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/vendor/zendframework/zend-expressive-fastroute/src/FastRouteRouter.php on line 51
_______________________________________________________________________________________________________________
Get this error after fresh clone of zend-expressive-skeleton:3.0.  I am running PHP 7.2 on a scotchbox.  I have tried several different versions of PHP, several different vagrant boxes, and editing the configuration files in apache.  I have removed all of the files in the repository and replaced it with a zend expressive 2 project and it loaded just fine.  I have also spun up a local PHP server and the page loaded just fine.  Sorry if this issue doesn't belong here, but I have tried everything on the vagrant side that I can think of, I felt the issue has to lie within the code.

### Code to reproduce the issue
A fresh clone of of zend-expressive-skeleton:3.0

### Expected results
The Zend Expressive home page template.

### Actual results
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/vendor/zendframework/zend-expressive-fastroute/src/FastRouteRouter.php on line 51

**Comment by webimpress** [comment]
@brock0124 This is the wrong repository for that issue - it should be reported in https://github.com/zendframework/zend-expressive-fastroute

I checked that line and we have there:
```php
    public const CACHE_TEMPLATE = <<< 'EOT'
<?php
return %s;
EOT;
```

Here is simplified class with just this lines:
https://3v4l.org/Po5A4
and as you can see we are getting that error only on PHP 5.6 and 7.0, definitely not on PHP 7.2.

Are you sure you are using PHP 7.2? I can see that scotchbox is using PHP 7.0 in free version and 7.2 in pro version (paid): https://github.com/scotch-io/scotch-box#scotch-box-35
What version are you using?

PHP 7.2 is fine. Expressive requires at least PHP 7.1, can't work on PHP 7.0.

**Comment by brock0124** [comment]
![scotchbox](https://user-images.githubusercontent.com/25236863/38169155-09de2a7e-3528-11e8-9e36-d12825fc928a.PNG)
Thank you for the reply and pointing in me in the right direction.  Regarding the PHP version, I have updated it myself.  Attached is a screenshot of the PHP version that is hosting the site in the scotchbox.

**Comment by Ocramius** [comment]
Careful about that: the CLI and the CGI version of PHP are likely different

**Comment by brock0124** [comment]
@Ocramius Thank you for your reply.  You were correct.  When running phpinfo() it told me I was running PHP 7.0 while the command line told me otherwise.  

`sudo a2dismod php7.0`
`sudo a2enmod php7.1`
`sudo service apache2 restart`

The code above resolved my issue.
