### ISSUE TITLE
Adding Bootstrap and jQuery JS files in Zend\View layout

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive-skeleton#44]
I wonder if it is a bug or done by intention. When the Bootstrap and jQuery JS files are added to the `Zend\View` layout the `headScript()` view helper is used.

https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/Resources/templates/zend-view-layout.phtml#L73

I think the `inlineScript()` view helper might be a better choice.

**Comment by weierophinney** [comment]
@RalfEggert Sounds good; feel free to submit a pull request!

**Comment by xtreamwayz** [comment]
I'm not sure why I used headScript(). I think I copied it from somewhere. The reason it's at the bottom is to speed up page loading.

**Comment by RalfEggert** [comment]
@weierophinney PR is there

**Comment by weierophinney** [comment]
Close with #45.
