### ISSUE TITLE
Directory naming convention

### ISSUE THREAD

**Issue by mtymek** [zendframework/zend-expressive-skeleton#55]
ZF2 skeleton uses convention where directories containing classes (reflecting namespace structure) are written with first letter in uppercase, while resource files are kept in directories starting with lower case letters. So we have:

```
config/
  module.config.php
src/
  App/
    Controller/
      IndexController.php
    Repository/
      AlbumRepo.php
view/
  index.phtml
  layout.phtml
```

etc.

In case of this repository, it is mixed, with no clear indication what to find under certain directory:

```
config/
  something.php
data/
  cache/
    .gitignore
src/
  ExpressiveInstaller/
    Resources/
      config/
        routes.php
    templates/
      plates-404.phtml
    config.php
    OptionalPackages.php
```

Is there a reason behind this convention? Perhaps this should be standardized to make browsing the code easier?

**Comment by weierophinney** [comment]
@mtymek You'll note that the only place that violates the convention is the `src/ExpressiveInstaller/` directory. This was to keep all source files together for purposes of autoloading. However, we also found it was far simpler to keep the assets that the installer uses under the same tree for two reasons:

- Easier to locate them within the installer
- Easier to remove them when installation is complete.

This latter point makes your question moot; the files under that tree are *removed after installation*, leaving you with a consistent tree on completion.
