### ISSUE TITLE
error handling and --no-dev argument

### ISSUE THREAD

**Issue by renanbr** [zendframework/zend-expressive-skeleton#63]
After install it with FastRoute, Zend ServiceManage, Plates and Whoops

```
composer create-project --no-dev "zendframework/zend-expressive-skeleton:^1.0@rc" expressive-1.0.0rc6
```

I got this error
```
Fatal error: Uncaught Error: Class 'Whoops\Run' not found in /Users/renan/Documents/Workspace/expressive-1.0.0rc6/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php:32
Stack trace:
#0 /Users/renan/Documents/Workspace/expressive-1.0.0rc6/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(693): Zend\ServiceManager\Factory\InvokableFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Whoops\\Run', NULL)
#1 /Users/renan/Documents/Workspace/expressive-1.0.0rc6/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(187): Zend\ServiceManager\ServiceManager->doCreate('Whoops\\Run')
#2 /Users/renan/Documents/Workspace/expressive-1.0.0rc6/vendor/zendframework/zend-expressive/src/Container/WhoopsErrorHandlerFactory.php(66): Zend\ServiceManager\ServiceManager->get('Whoops\\Run')
#3 /Users/renan/Documents/Workspace/expressive-1.0.0rc6/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(693): Zend\Expressive\Container\WhoopsErrorHandlerFactory->__invoke(Object(Zend\Serv in /Users/renan/Documents/Workspace/expressive-1.0.0rc6/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php on line 32
```

It was my mistake, because `filp/whoops` is a dev dependence, but I think it makes no sense to ask which error handler to install in this case.

I suggest:
- skip error handler prompt if `--no-dev` is given; __or__
- move `filp/whoops` to the `require` entries.

**Comment by weierophinney** [comment]
We're working on a solution; please see #62.

Whoops needs to be a dev requirement; you typically do not want such functionality in your production servers. The problem, as noted in #62 and elsewhere, is that if we do not use the `--no-dev` switch, all the development requirements *from before the installer updates the composer.json* are used, which leads to incorrect dependencies being installed. (*All* the routers and *all* the template implementations, which I observed leading to selecting different dependency versions than occur in a regular install.)

So, we need to find a fix to that specific situation, and not a workaround. We'll get there, hopefully before the stable release.

Closing as a duplicate.
