### ISSUE TITLE
Update composer.json for 1.0 release

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-expressive-skeleton#74]
I wonder if the `require` section should be updated to just use the 1.0 stable release of `Zend\Expressive` now?

https://github.com/zendframework/zend-expressive-skeleton/blob/master/composer.json#L21

And are the other requirements up to date?

**Comment by xtreamwayz** [comment]
See PR #72.

**Comment by RalfEggert** [comment]
Missed that. Sorry. Closing
