### ISSUE TITLE
huge var_dump output in zend-view-error.phtml

### ISSUE THREAD

**Issue by yuriitvardyi** [zendframework/zend-expressive-skeleton#77]
If `$this->error` is an **Exception** instance the **var_dump** function causes a huge output (over 10MB) in the [zend-view-error.phtml](https://github.com/zendframework/zend-expressive-skeleton/blob/6f1e5629470ed18c9b9128a8b4eb9a0299a52e29/src/ExpressiveInstaller/Resources/templates/zend-view-error.phtml#L12) template.

**Comment by xtreamwayz** [comment]
The var_dump was never meant to make it into a stable release. Exceptions including stack traces can get pretty big. If you need something to debug your app, use tools like whoops.

I've made a PR for this: #78
