### ISSUE TITLE
composer install --no-dev and Whoops problem

### ISSUE THREAD

**Issue by tasmaniski** [zendframework/zend-expressive-skeleton#82]
During the installation I choose to install Whoops but also FastRoute, ZendServiceManager etc.
If I install with no dev option 
`composer install --no-dev `

I can see that only `"filp/whoops": "^1.1 || ^2.0"` is added in **"require-dev"** section (which is not installed during the composer install process).

Shouldn't Whoops be added in "required" section as rest of dependencies?

**Comment by weierophinney** [comment]
No, it should not. Whoops displays exception details, which should never be displayed in production. Fit that reason, it's a *development* dependency, and enabled in *local* configuration files (which are excluded from commit via `.gitignore`). 

As such, in you use the `--no-dev` option, you need to make sure you have a production-appropriate error handler configured.

**Comment by tasmaniski** [comment]
Yes, that makes a sense. 
Tnx!
