### ISSUE TITLE
Remove composer.lock from .gitignore

### ISSUE THREAD

**Issue by jonsa** [zendframework/zend-expressive-skeleton#87]
Since this is a project skeleton shouldn't the [composer recommendations](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file) be followed when the consumer of this repo decides to push it the his/her vsc?

I can understand from a maintainer point of view, of this repo, that it limits the possibility of a composer.lock file to be commit. But perhaps it should be included in the interactive install process to have it removed?

**Comment by weierophinney** [comment]
Hi, @jonsa - Yes, having it in the repo is a bit of a problem, as it locks the installation to specific revisions, requiring users to immediately run a `composer update` to get new versions; this in turn creates maintenance overhead on our part, as we have to be constantly updating and pushing new tags of the skeleton whenever we release new versions of dependencies.

However, as you note, having an installation step that removes the `composer.lock` entry from the `.gitignore` file would work fine. Would you be willing to try and tackle that in a pull request?
