### ISSUE TITLE
routing definitions and action classes configuration should be gathered

### ISSUE THREAD

**Issue by renanbr** [zendframework/zend-expressive-skeleton#9]
I didn't find a group list, so I've decided open this issue (maybe a support issue). I'm trying use `zend-expressive-skeleton` and I faced with a usability issue. When a need to add a new action - and if I follow the practices for HomePageAction and PingAction in config flies - I have to change two files: `dependencies.global.php` and `routes.global.php` I prefer do it into `routes.global.php` only, because everything related to routing is in this single file.

Why route definitions are isolated from action classes configuration?

**Comment by weierophinney** [comment]
You can use the zf-contributors list, but this is likely a better place.

With regards to putting the middleware dependencies in `routes.global.php`, I tend to agree with you. I'm going to create PRs for both zend-expressive and this repo to make that update.

**Comment by weierophinney** [comment]
Actually, only affects the docs, so the relevant PR is in zendframework/zend-expressive#163.
