### ISSUE TITLE
ReflectionException at serve

### ISSUE THREAD

**Issue by fabiopellati** [zendframework/zend-expressive-skeleton#92]
I've follow instuctions at README.md 
when I run 
`composer serve`
and oll other composer command
it throw this exceptions

```
[ReflectionException]
Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does not exist

[ErrorException]
Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository::whatProvides() should be compatible with Composer\Repository\ComposerRepository::whatProvides(Composer\DependencyResolver\Pool $pool, $name, $bypassFilters = false)
```

**Comment by weierophinney** [comment]
Looks like you have bad composer plugins installed. Please try using a fresh install of composer; if you continue to have issues, please report against [composer](https://github.com/composer/composer).
