### ISSUE TITLE
fresh install not working 

### ISSUE THREAD

**Issue by bcgould04** [zendframework/zend-expressive-skeleton#94]
Zend\View\Renderer\PhpRenderer::render: Unable to render template "error::404"; resolver could not resolve to a file -- installed with composer - zend view - zend router - zend service manager - whoops

**Comment by xtreamwayz** [comment]
If you choose the minimal version (first question answered with yes), it doesn't install templates. You need to either create those yourself or choose "No" for a full installation including an example and error templates.

**Comment by bcgould04** [comment]
I did choose the full install - deleted it, tried it again, and still same issue - had another developer also try it - still same issue - 

[30;46mMinimal skeleton? (no default middleware, templates, or assets; configuration only)[39;49m
  [[33my[39m] Yes (minimal)
  [[33mn[39m] No (full; recommended)
  Make your selection [33m(No)[39m: 2

  [30;46mWhich router do you want to use?[39;49m
  [[33m1[39m] Aura.Router
  [[33m2[39m] FastRoute
  [[33m3[39m] Zend Router
  Make your selection or type a composer package name and version [33m(FastRoute)[39m: 3
  - Adding package [32mzendframework/zend-expressive-zendrouter[39m ([33m^1.0[39m)
  - Copying [32m/config/autoload/routes.global.php[39m

  [30;46mWhich container do you want to use for dependency injection?[39;49m
  [[33m1[39m] Aura.Di
  [[33m2[39m] Pimple
  [[33m3[39m] Zend ServiceManager
  Make your selection or type a composer package name and version [33m(Zend ServiceManager)[39m: 3
  - Adding package [32mzendframework/zend-servicemanager[39m ([33m^2.7.3 || ^3.0[39m)
  - Adding package [32mocramius/proxy-manager[39m ([33m^1.0 || ^2.0[39m)
  - Copying [32m/config/container.php[39m

  [30;46mWhich template engine do you want to use?[39;49m
  [[33m1[39m] Plates
  [[33m2[39m] Twig
  [[33m3[39m] Zend View [33minstalls Zend ServiceManager[39m
  [[33mn[39m] None of the above
  Make your selection or type a composer package name and version [33m(n)[39m: 3

**Comment by xtreamwayz** [comment]
That's strange. The last release is from April 21st so nothing changed last week.

Only one question, why do you have `2` as the answer for the first question? It should be `y` or `n`.

**Comment by bcgould04** [comment]
was in a hurry - thats from the first time. i hit N the second time after deleting and reinstalling. No is default anyway so it should do the full install when i hit 2 - or so is my understanding. I thought it strange, tried it twice, called another guy, and had him also run through it. not sure - but if you cant recreate the problem then it must be between the keyboard and the chair

**Comment by xtreamwayz** [comment]
What does it say after the last question?

If it installs the minimum version you get something like this:

```
Remove installer
Removing default middleware classes and factories
Removing default middleware class tests
Removing assets
Removing composer.lock from .gitignore
Removing Expressive installer classes, configuration, and tests
```

**Comment by xtreamwayz** [comment]
I've tried several options for the first question: `2`, `N`, `n`

The only one that works as intended is lower case `n`. All others fall back to the first answer which is removing the assets. We might need to change that or force a `y` or `n` answer only.

**Comment by bcgould04** [comment]
cool. so 2 and N arent allowed - only n - got it - i guess last week I just hit n - and this week, not paying attention hit 2 and then N..

**Comment by xtreamwayz** [comment]
So it works for you with lower case `n`?

**Comment by bcgould04** [comment]
yes

**Comment by xtreamwayz** [comment]
Great. I'll try to figure out something to prevent this from happening again.
