### ISSUE TITLE
Integration for zend-component-installer, possible?

### ISSUE THREAD

**Issue by gabbydgab** [zendframework/zend-expressive-skeleton#96]
Just like ZF3, you can integrate module/component with ease.  

Possible? Or does this break the context of what Expressive is?

**Comment by weierophinney** [comment]
zend-component-installer already supports components that expose a ConfigProvider class in their namespace. If you follow the cookbook for creating modular applications, that feature helps facilitate the process.

We plan to integrate the feature by default in the skeleton in either a 1.1 or later release.
