### ISSUE TITLE
ocramius/proxy-manager needed?

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-expressive-skeleton#99]
Is there a reason why ocramius/proxy-manager is in require-dev?
The tests are running fine without it.

**Comment by Ocramius** [comment]
Not required, indeed, but needed for using lazy services.

Can you look up who added it, and why?

**Comment by Koopzington** [comment]
The package was added by @xtreamwayz in [This](https://github.com/zendframework/zend-expressive-skeleton/commit/1848cf59d4c1fd896b3a0d61aed5774d5ee61585) commit.
Downloaded a Tarball of that version and searched for anything mentioning "Proxy" and found nothing but the package name in the composer.json and the ExpressiveInstaller config.php
I'm not saying Lazy Services are bad. If this package is only included to encourage using them, i'm all in, but it feels like the skeleton has even more dependencies than the zend-mvc skeleton....

**Comment by xtreamwayz** [comment]
I added this when during development. Most likely because I copied dependencies from somewhere else. As far as I know the proxy-manager is nowhere used and could be used.

> but it feels like the skeleton has even more dependencies than the zend-mvc skeleton....

I'm not sure how you get that feeling. It has only 5 dependencies and they all are being used and speak for their self:

        "php": "^5.5 || ^7.0",
        "roave/security-advisories": "dev-master",
        "zendframework/zend-expressive": "^1.0",
        "zendframework/zend-expressive-helpers": "^2.0",
        "zendframework/zend-stdlib": "^2.7 || ^3.0"

If you are referring to all the other dev-requirements, I've added those because they were used in tests or I needed them for code completion. However the code has changed during development so I'm not sure which are obsolete now.

**Comment by xtreamwayz** [comment]
Found them. Have a look in the [config](https://github.com/zendframework/zend-expressive-skeleton/tree/master/src/ExpressiveInstaller/Resources/config) sources.

**Comment by xtreamwayz** [comment]
And the proxy manager is installed by default as well: https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/config.php#L109

**Comment by Koopzington** [comment]
The skeleton itself might not have that many dependencies but the dependencies themselves have several others. But there's nothing we can do about that.
Anyways... would it be okay if i create a PR to remove that particular line you posted (which would let us get rid off zendframework/zend-code, zendframework/zend-eventmanager and ocramius/package-versions). 

While we're on it: I've discovered that even if you decide not to use filp/whoops as ErrorHandler, [it get's added to require-dev](https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/config.php#L18) by this [piece of code](https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/OptionalPackages.php#L331). I guess making that require-dev array empty should do the trick.
